import { describe, it, expect } from 'vitest';

import {
  getPasswordHash,
  verifyPassword,
  createAccessToken,
  decodeToken,
} from '../src/core/security';

describe('password hashing', () => {
  it('round-trips a password', () => {
    const hash = getPasswordHash('s3cr3t-p@ss');
    expect(hash.startsWith('$2')).toBe(true); // bcrypt hash prefix
    expect(verifyPassword('s3cr3t-p@ss', hash)).toBe(true);
    expect(verifyPassword('wrong', hash)).toBe(false);
  });

  it('verifies a real passlib-generated $2b$ hash (existing users keep working)', () => {
    // Generated by Python's passlib(bcrypt) — the exact format stored by the
    // old FastAPI backend. bcryptjs must verify it so existing users log in.
    const passlibHash = '$2b$12$VbJtdUEHBLRNmBO0RSxqmeWddfQOzSgVsP.IIViEsf5Efw1GmJME6';
    expect(passlibHash.startsWith('$2b$')).toBe(true);
    expect(verifyPassword('correct horse', passlibHash)).toBe(true);
    expect(verifyPassword('wrong horse', passlibHash)).toBe(false);
  });
});

describe('JWT', () => {
  it('creates and decodes a token with the email subject', () => {
    const token = createAccessToken('user@example.com');
    const data = decodeToken(token);
    expect(data).not.toBeNull();
    expect(data?.sub).toBe('user@example.com');
  });

  it('returns null for a malformed token', () => {
    expect(decodeToken('not-a-jwt')).toBeNull();
  });

  it('returns null for an expired token', () => {
    const token = createAccessToken('user@example.com', -1); // already expired
    expect(decodeToken(token)).toBeNull();
  });
});
